# Generated by Django 4.1.4 on 2023-01-25 07:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomCat', models.CharField(max_length=255)),
                ('slug', models.SlugField(null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='kikou',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='annonce',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='annonce',
            name='title',
        ),
        migrations.AddField(
            model_name='annonce',
            name='date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='annonce',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annonce',
            name='modalité',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='annonce',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='annonce',
            name='tarif',
            field=models.DecimalField(decimal_places=5, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/uploads'),
        ),
        migrations.AddField(
            model_name='annonce',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to='API.categorie'),
        ),
    ]
