# Generated by Django 4.1.4 on 2023-01-25 10:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_categorie_kikou_remove_annonce_instructor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thème',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomTheme', models.CharField(max_length=255)),
                ('slug', models.SlugField(null=True, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='annonce',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='annonce',
            name='thème',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to='API.thème'),
        ),
    ]
