# Generated by Django 4.1.4 on 2023-01-25 16:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('API', '0003_thème_alter_annonce_date_annonce_thème'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='favorites',
            field=models.ManyToManyField(blank=True, default=None, related_name='favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
