# Generated by Django 4.1.4 on 2023-01-26 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_annonce_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='tarif',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Price'),
        ),
    ]
