# Generated by Django 4.1.4 on 2023-01-26 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('API', '0005_alter_annonce_tarif'),
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_message', models.CharField(blank=True, max_length=100)),
                ('corps', models.TextField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('annonce', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message', to='API.annonce')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='reponse_message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corps', models.TextField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('nom_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='réponse', to='API.message')),
            ],
        ),
    ]
