# Generated by Django 4.1.4 on 2023-01-26 04:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('API', '0006_message_reponse_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='déposé_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='thème',
            name='catégorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thème', to='API.categorie'),
        ),
        migrations.AddField(
            model_name='thème',
            name='thème_id',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='nomCat',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='auteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='corps',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='message',
            name='nom_message',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reponse_message',
            name='auteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reponse_message',
            name='corps',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='reponse_message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='reponse_message',
            name='nom_message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='réponse', to='API.message'),
        ),
        migrations.AlterField(
            model_name='thème',
            name='nomTheme',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
