# Generated by Django 4.1.4 on 2023-01-26 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_annonce_déposé_par_thème_catégorie_thème_thème_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='kikou',
        ),
        migrations.RemoveField(
            model_name='thème',
            name='thème_id',
        ),
    ]
