# Generated by Django 4.1.4 on 2023-01-27 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_wilaya_annonce_adresse_commune_annonce_wilaya_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reponse_message',
            name='auteur',
        ),
        migrations.RemoveField(
            model_name='reponse_message',
            name='nom_message',
        ),
        migrations.RenameField(
            model_name='annonce',
            old_name='favorites',
            new_name='favoris',
        ),
        migrations.RemoveField(
            model_name='categorie',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='commune',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='thème',
            name='slug',
        ),
        migrations.DeleteModel(
            name='message',
        ),
        migrations.DeleteModel(
            name='reponse_message',
        ),
    ]
