# Generated by Django 4.1.4 on 2023-01-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0011_rename_catégorie_thème_categorie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='titre',
            field=models.TextField(blank=True, null=True),
        ),
    ]
