# Generated by Django 4.1.4 on 2023-01-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0012_annonce_titre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='modalité',
            field=models.CharField(choices=[('En-Ligne', 'En-Ligne'), ('Hors-Ligne', 'Hors-Ligne')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='titre',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
