# Generated by Django 4.1.4 on 2023-01-28 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0013_alter_annonce_modalité_alter_annonce_titre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thème',
            name='categorie',
        ),
    ]
