# Generated by Django 4.1.4 on 2023-01-28 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0014_remove_thème_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='thème',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thème', to='API.categorie'),
        ),
    ]
