# Generated by Django 4.1.4 on 2023-01-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0015_thème_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='nomCat',
            field=models.CharField(choices=[('Primaire', 'Primaire'), ('Collège', 'Collège'), ('Lycée', 'Lycée')], max_length=255, null=True),
        ),
    ]
