# Generated by Django 4.1.4 on 2023-01-28 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0016_annonce_nomcat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thème',
            name='categorie',
        ),
    ]
