# Generated by Django 4.1.4 on 2023-01-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0017_remove_thème_categorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annonce',
            name='categorie',
        ),
        migrations.AlterField(
            model_name='annonce',
            name='thème',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Categorie',
        ),
        migrations.DeleteModel(
            name='Thème',
        ),
    ]
