# Generated by Django 4.1.4 on 2023-01-28 16:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('API', '0018_remove_annonce_categorie_alter_annonce_thème_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='inscrit',
            field=models.ManyToManyField(blank=True, default=None, related_name='inscrit', to=settings.AUTH_USER_MODEL),
        ),
    ]
