# Generated by Django 4.1.4 on 2023-01-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0020_offre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offre',
            old_name='Wilaya',
            new_name='Annonce',
        ),
        migrations.AddField(
            model_name='offre',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
