# Generated by Django 4.1.4 on 2023-01-28 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0021_rename_wilaya_offre_annonce_offre_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offre',
            name='slug',
        ),
    ]
