# Generated by Django 4.1.4 on 2023-01-28 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0022_remove_offre_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annonce',
            name='inscrit',
        ),
    ]
