# Generated by Django 4.1.4 on 2023-01-28 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0023_remove_annonce_inscrit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offre',
            name='Annonce',
        ),
        migrations.AddField(
            model_name='offre',
            name='Annonce',
            field=models.ManyToManyField(to='API.annonce'),
        ),
    ]
