# Generated by Django 4.1.4 on 2023-01-28 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0024_remove_offre_annonce_offre_annonce'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offre',
            name='Annonce',
        ),
        migrations.AddField(
            model_name='offre',
            name='Annonce',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API.annonce'),
        ),
    ]
