# Generated by Django 4.1.4 on 2023-01-29 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('API', '0025_remove_offre_annonce_offre_annonce'),
    ]

    operations = [
        migrations.AddField(
            model_name='offre',
            name='déposé',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='déposé_par', to=settings.AUTH_USER_MODEL),
        ),
    ]
