# Generated by Django 4.1.4 on 2023-01-29 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('API', '0026_offre_déposé'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offre_perso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('déposé', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('offre', models.ManyToManyField(to='API.offre')),
            ],
        ),
    ]
