# Generated by Django 4.1.4 on 2023-01-29 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0027_offre_perso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offre',
            old_name='déposé',
            new_name='user',
        ),
    ]
