# Generated by Django 4.1.4 on 2023-01-26 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prénom', models.CharField(max_length=50)),
                ('Nom', models.CharField(max_length=50)),
                ('Num_tel', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('Mot_de_passe', models.CharField(max_length=100)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
    ]
